
# 🌾 AI for Agriculture – Consolidated ML Story Notebook
## From Field Problems to Trustworthy AI Decisions

**Audience:** Agriculture-focused learners (non-programmers)  
**Approach:** Storytelling + farming analogies  

> AI should behave like a good farmer: observe, test, verify, and improve.
---



## 1️⃣ Supervised vs Unsupervised Learning

### 🌱 Why study this?
Different farm problems need either known answers or discovery.

### 🚜 Farming Scenario
Teaching crop vs weed vs discovering soil zones.

### 🛠️ How to handle the scenario (Concept)
Use labels for supervised, patterns for unsupervised.


In [ ]:

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

rainfall = np.array([[200],[180],[220],[210]])
yield_kg = np.array([3200,3000,3500,3400])
sup = LinearRegression()
sup.fit(rainfall, yield_kg)
sup.predict([[205]])

soil = np.array([[6.5,30],[7.2,45],[6.6,32],[7.5,50]])
KMeans(n_clusters=2, random_state=0).fit_predict(soil)

array([0, 1, 0, 1], dtype=int32)


### 📊 Interpretation of Output
Supervised predicts known outputs; unsupervised groups similar inputs.

### ⚠️ Challenges & Best Practices
Choosing wrong approach leads to misleading advice.
---



## 2️⃣ Train–Test Split

### 🌱 Why study this?
Avoid risky full-farm rollout.

### 🚜 Farming Scenario
Trial plot before production.

### 🛠️ How to handle the scenario (Concept)
Split data into training and testing.


In [ ]:

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "Rainfall":[200,180,220,210,190,230],
    "Yield":[3200,3000,3500,3400,3100,3600]
})

X = df[["Rainfall"]]
y = df["Yield"]
train_test_split(X, y, test_size=0.3, random_state=42)

[   Rainfall
 5       230
 2       220
 4       190
 3       210,
    Rainfall
 0       200
 1       180,
 5    3600
 2    3500
 4    3100
 3    3400
 Name: Yield, dtype: int64,
 0    3200
 1    3000
 Name: Yield, dtype: int64]


### 📊 Interpretation of Output
Training teaches; testing verifies.

### ⚠️ Challenges & Best Practices
Data leakage reduces trust.
---



## 3️⃣ Cross-Validation

### 🌱 Why study this?
One season can be lucky.

### 🚜 Farming Scenario
Testing seeds across seasons.

### 🛠️ How to handle the scenario (Concept)
Rotate test sets and average results.


In [3]:

from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression

kf = KFold(n_splits=3, shuffle=True, random_state=42)
scores = []
for tr, te in kf.split(X):
    m = LinearRegression()
    m.fit(X.iloc[tr], y.iloc[tr])
    scores.append(m.score(X.iloc[te], y.iloc[te]))
scores

[0.9044897959183683, 0.8200000000000001, 0.9552491301988576]


### 📊 Interpretation of Output
Stable scores mean reliable model.

### ⚠️ Challenges & Best Practices
More folds increase computation.
---



## 4️⃣ Bias vs Variance

### 🌱 Why study this?
Avoid too simple or too complex models.

### 🚜 Farming Scenario
Generic advice vs memorizing last season.

### 🛠️ How to handle the scenario (Concept)
Balance complexity.


In [4]:

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

simple = LinearRegression()
simple.fit(X, y)
simple.predict([[205]])

complex_m = make_pipeline(PolynomialFeatures(5), LinearRegression())
complex_m.fit(X, y)
complex_m.predict([[205]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


array([3300.68546925])


### 📊 Interpretation of Output
Balanced models generalize best.

### ⚠️ Challenges & Best Practices
Small data exaggerates overfitting.
---



## 5️⃣ Hyperparameter Tuning

### 🌱 Why study this?
Correct settings improve performance.

### 🚜 Farming Scenario
Calibrating sprayer settings.

### 🛠️ How to handle the scenario (Concept)
Search parameter combinations.


In [5]:

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

params = {"n_estimators":[50,100], "max_depth":[2,4,None]}
grid = GridSearchCV(RandomForestRegressor(random_state=0), params, cv=3)
grid.fit(X, y)
grid.best_params_

{'max_depth': 4, 'n_estimators': 50}


### 📊 Interpretation of Output
Best parameters represent sweet spot.

### ⚠️ Challenges & Best Practices
Grid search can be slow.
---



## 6️⃣ Scikit-Learn Basics

### 🌱 Why study this?
Unified workflow reduces errors.

### 🚜 Farming Scenario
Same tractor, different tools.

### 🛠️ How to handle the scenario (Concept)
Use pipelines.


In [6]:

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

pipe = Pipeline([
    ("scale", StandardScaler()),
    ("model", LinearRegression())
])
pipe.fit(X, y)
pipe.predict([[205]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([3300.])


### 📊 Interpretation of Output
Pipeline ensures safe workflow.

### ⚠️ Challenges & Best Practices
Skipping steps causes leakage.
---



## 7️⃣ Linear Regression

### 🌱 Why study this?
Find yield recipe.

### 🚜 Farming Scenario
Quantify rainfall effect.

### 🛠️ How to handle the scenario (Concept)
Fit linear model.


In [12]:

model = LinearRegression()
model.fit(X, y)
model.coef_, model.intercept_

(array([12.57142857]), np.float64(722.8571428571431))


### 📊 Interpretation of Output
Coefficients explain influence.

### ⚠️ Challenges & Best Practices
Assumes linearity.
---



## 8️⃣ Regression Evaluation

### 🌱 Why study this?
Weigh predictions.

### 🚜 Farming Scenario
Compare expected vs actual yield.

### 🛠️ How to handle the scenario (Concept)
Use MAE, RMSE, R².


In [13]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

pred = model.predict(X)
mean_absolute_error(y, pred), np.sqrt(mean_squared_error(y, pred)), r2_score(y, pred)

(20.952380952380963, np.float64(23.904572186687872), 0.9877551020408163)


### 📊 Interpretation of Output
Lower error, higher R² is better.

### ⚠️ Challenges & Best Practices
High accuracy may hide big mistakes.
---



## 9️⃣ Logistic Regression

### 🌱 Why study this?
Binary risk decisions.

### 🚜 Farming Scenario
Frost damage yes/no.

### 🛠️ How to handle the scenario (Concept)
Predict probability.


In [9]:

from sklearn.linear_model import LogisticRegression

Xc = [[2,90],[4,85],[6,70],[8,60]]
yc = [1,1,0,0]
clf = LogisticRegression()
clf.fit(Xc, yc)
clf.predict_proba([[3,88]]), clf.predict([[3,88]])

(array([[0.00654681, 0.99345319]]), array([1]))


### 📊 Interpretation of Output
Probability supports early warnings.

### ⚠️ Challenges & Best Practices
Threshold choice matters.
---



## 🔟 Decision Trees

### 🌱 Why study this?
Explainable rules.

### 🚜 Farming Scenario
Crop diagnostic chart.

### 🛠️ How to handle the scenario (Concept)
Learn decision rules.


In [10]:

from sklearn.tree import DecisionTreeClassifier

Xd = [[1,1],[1,0],[0,0]]
yd = ["Fungal","Nutrient","Healthy"]
tree = DecisionTreeClassifier(random_state=0)
tree.fit(Xd, yd)
tree.predict([[1,1]])

array(['Fungal'], dtype='<U8')


### 📊 Interpretation of Output
Decisions follow human logic.

### ⚠️ Challenges & Best Practices
Trees can overfit.
---



## 1️⃣1️⃣ Feature Importance

### 🌱 Why study this?
Focus on what matters.

### 🚜 Farming Scenario
Ignoring low-impact factors.

### 🛠️ How to handle the scenario (Concept)
Extract importance from trees.


In [11]:

from sklearn.ensemble import RandomForestRegressor
import pandas as pd

Xf = pd.DataFrame({
    "Rainfall":[200,180,220],
    "Soil_Moisture":[30,28,35],
    "Humidity":[80,75,85]
})
yf = [3200,3000,3500]

rf = RandomForestRegressor(random_state=0)
rf.fit(Xf, yf)
pd.Series(rf.feature_importances_, index=Xf.columns)

,0
Rainfall,0.259259
Soil_Moisture,0.448343
Humidity,0.292398



### 📊 Interpretation of Output
Higher importance means stronger influence.

### ⚠️ Challenges & Best Practices
Importance may vary regionally.
---



## 🌱 Final Message

You learned how AI thinks like a farmer:
- Observe
- Test
- Validate
- Improve

**Good data + Good testing = Trustworthy AI**
