In [ ]:
# Install NumPy
!pip install numpy
# Import in your script
import numpy as np
# Check version
print(np.__version__)

2.0.2


In [ ]:
# Traditional Python list
temps_list = [72, 75, 68, 71, 74, 69, 73]
# Convert to NumPy array
import numpy as np
temps_array = np.array([72, 75, 68, 71, 74, 69, 73])
print(temps_array)
# Output: [72 75 68 71 74 69 73]
print(type(temps_array))
# Output: <class 'numpy.ndarray'>

[72 75 68 71 74 69 73]
<class 'numpy.ndarray'>


In [ ]:
# Temperatures from 3 sensors over 5 days
sensor_temps = np.array([
 [72, 70, 71], # Day 1
 [75, 73, 74], # Day 2
 [68, 67, 69], # Day 3
 [71, 70, 72], # Day 4
 [74, 72, 73] # Day 5
])
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [7]:

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [9]:
arr = np.array([1.5, 2.7, 3.2])
print(arr.dtype)

float64


In [10]:
arr = np.array([1,2,3])
print(arr.itemsize)

8


In [16]:
crops = np.array(['corn', 'wheat', 'soy', 'barley', 'oats'])
# Access single element (zero-indexed)
print(crops[0])
print(crops[-1])
# Access multiple elements
print(crops[1:4])
print(crops[::2])

corn
oats
['wheat' 'soy' 'barley']
['corn' 'soy' 'oats']


In [17]:
# Soil pH readings (3 fields × 4 samples)
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
# Single element: row 1, column 2
print(ph_levels[1, 2])

6.9


In [18]:
# Entire row 0
print(ph_levels[0, :])

[6.5 6.8 6.3 6.7]


In [19]:
# Entire column 3
print(ph_levels[:, 3])

[6.7 7.2 6.3]


In [20]:
# First 2 rows, first 3 columns
sub_array = ph_levels[0:2, 0:3]
print(sub_array)

[[6.5 6.8 6.3]
 [7.1 7.  6.9]]


In [21]:

# Every other row, all columns
print(ph_levels[::2, :])

[[6.5 6.8 6.3 6.7]
 [6.2 6.4 6.1 6.3]]


In [22]:
temperatures = np.array([72, 85, 91, 68, 95, 70, 88])
# Create a boolean array (mask)
hot_days = temperatures > 85
print(hot_days)

[False False  True False  True False  True]


In [23]:
# Use mask to filter original array
print(temperatures[hot_days])

[91 95 88]


In [24]:
# Can do it in one line
print(temperatures[temperatures > 85])

[91 95 88]


In [25]:
# Combine conditions with & (and), | (or)
moderate = temperatures[(temperatures >= 70) &
(temperatures <= 85)]
print(moderate)

[72 85 70]


In [26]:
# Find extreme values (very hot OR very cold)
extreme = temperatures[(temperatures > 90) |
(temperatures < 70)]
print(extreme)

[91 68 95]


In [27]:
# Crop yields in tons
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
# Add arrays
total_yield = field_a + field_b
print(total_yield)

[238 275 280 260]


In [28]:
# Subtract to find difference
difference = field_a - field_b
print(difference)

[ 2 -5  4 -4]


In [29]:
# Multiply each by a constant
doubled = field_a * 2
print(doubled)

[240 270 284 256]


In [34]:

# Square roots
areas = np.array([100, 144, 225, 169])
sides = np.sqrt(areas)
# [10. 12. 15. 13.]
# Exponentiation
growth = np.exp([0, 1, 2])
# [1. 2.718 7.389]
# Logarithms
np.log10([10, 100, 1000])
# [1. 2. 3.]

array([1., 2., 3.])

In [37]:

prices = np.array([19.99, 24.51, 30.25])
# Round to nearest integer
np.round(prices)
# [20. 25. 30.]
# Floor (round down)
np.floor(prices)
# [19. 24. 30.]
# Ceiling (round up)
np.ceil(prices)
# [20. 25. 31.]

array([20., 25., 31.])